export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";

export const ADD_NEW_ROBOT = "ADD_NEW_ROBOT";

export const DELETE_ROBOT = "DELETE_ROBOT";

export const ADD_FETCHED_ROBOTS_TO_STATE = "ADD_FETCHED_ROBOTS_TO_STATE";

export const FETCHING_ERROR = "FETCHING_ERROR";

export const CHANGE_ROBOT_INFO = "CHANGE_ROBOT_INFO";